//
//  Game.m
//  YouMeAndWords_v1
//
//  Created by Raj Kandati on 3/26/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "Game.h"
#import "YouMeAndWordsConstants.h"

@implementation Game


+ (NSMutableDictionary *)getGameForGameNumber:(int)gameNumber
{
    //Probably use the id to get the game from database...
    NSMutableDictionary *game = [[NSMutableDictionary alloc] init];
    
    NSString *gameWordStrings = @"ADE;AID;AIN;AIR;AND;ANE;ANI;ANN;ARD;ARE;AWE;AWN;DAE;DAN;DAW;DEA;DEE;DEI;DEN;DEW;DIA;DIE;DIN;DNA;EAN;EAR;EEN;END;ENE;ERA;ERE;ERN;EWE;IDA;IDE;IED;INN;INR;IRA;IRE;NAD;NAE;NAN;NAW;NED;NEE;NEW;NID;NIE;NNE;NNW;NRA;RAD;RAI;RAN;RAW;RED;REE;REI;REN;REW;RIA;RID;RIN;RNA;WAD;WAE;WAI;WAN;WAR;WED;WEE;WEI;WEN;WIN;ADEN;AIDE;AIRE;ANEW;ANNE;ARID;AWED;DANE;DARE;DARI;DARN;DAWN;DEAN;DEAR;DEER;DERE;DINE;DIRE;DRAW;DREE;DREW;EARN;EDEN;EIRA;EIRE;ENID;ERIE;ERIN;ERNE;EWER;IDEA;IRAN;NARD;NEAR;NEED;NERD;NIDE;NINA;NINE;NRNA;RAID;RAIN;RAND;RANI;READ;REDE;REED;REID;REIN;REND;RIDE;RIND;WADE;WADI;WAIN;WAIR;WAND;WANE;WARD;WARE;WARN;WEAN;WEAR;WEED;WEEN;WEER;WEIR;WEND;WERE;WIDE;WIND;WINE;WIRE;WREN;AERIE;AIDER;AIRED;AWNED;DEWAR;DINAR;DINER;DIWAN;DRAIN;DRAWN;DWINE;EARED;EDWIN;EIDER;ENDER;INANE;INDRA;INNED;INNER;IRADE;IRENA;NADIR;NEWER;NINER;RANEE;RANID;REDAN;REDIA;RENEW;RENIN;REWIN;WADER;WANED;WEIRD;WIDEN;WIDER;WINED;WIRED;WRIED;AENEID;ANDREW;DAIREN;DARWIN;DEARIE;DENIER;DERAIN;DEWIER;DINNER;DRAWEE;EARNED;EDIRNE;ENDEAR;ENNEAD;ENWIND;INANER;INDENE;INWARD;NARINE;NEARED;NEREID;NEWARI;RAINED;REINED;WANDER;WANNED;WANNER;WARDEN;WARNED;WEANED;WIENER;WINDER;WINNER;ADENINE;INDRAWN;NARDINE;WEARIE";
    NSArray *gameWords = [gameWordStrings componentsSeparatedByString:@";"];
    
    NSString *gameLetters = @"N,W,E,I,N,D,R,A,E";
    NSArray *gameLetterArray = [gameLetters componentsSeparatedByString:@","];
    
    [game setObject:gameWords forKey:GAME_WORDS_KEY];
    [game setObject:gameLetterArray forKey:GAME_LETTERS_KEY];
    
    return game;
    
}




@end
