//
//  YouMeAndWordsConstants.h
//  YouMeAndWords
//
//  Created by Raj Kandati on 3/20/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#define ALPHABET_WIDTH 60
#define ALPHABET_WIDTH_SMALL 30
#define ALPHABET_HEIGHT 60
#define ALPHABET_HEIGHT_SMALL 30


#define NUMBERS_OF_COLUMNS_IN_GRID 3
#define NUMBERS_OF_ROWS_IN_GRID 3

#define BRODER_BETWEEN_CELLS_IN_GRID 10
#define BRODER_BETWEEN_CELLS_IN_GRID_SMALL 5

#define X_ORIGIN_OF_GRID 60
#define X_ORIGIN_OF_GRID_SMALL 110


#define Y_ORIGIN_OF_GRID 100
#define Y_ORIGIN_OF_GRID_SMALL 25

#define SCORE_WIDTH 10
#define SCORE_WIDTH_SMALL 8

#define SCORE_HEIGHT 10
#define SCORE_HEIGHT_SMALL 8

#define SCORE_X_ORIGIN ALPHABET_WIDTH -12
#define SCORE_X_ORIGIN_SMALL ALPHABET_WIDTH_SMALL - 10


#define SCORE_Y_ORIGIN ALPHABET_HEIGHT - 18
#define SCORE_Y_ORIGIN_SMALL ALPHABET_HEIGHT_SMALL - 13

#define GAME_LETTERS_KEY @"GAME_LETTERS_KEY"
#define GAME_WORDS_KEY @"GAME_WORDS_KEY"
#define UUID_USER_DEFAULTS_KEY @"UUID"

#define PLAYER_NAME @"PLAYER_NAME"
#define LAST_GAME_PLAYED @"LAST_GAME_PLAYED"
#define TOTAL_NUMBER_OF_WORDS_CREATED @"TOTAL_NUMBER_OF_WORDS_CREATED"
#define SIX_PLUS_LETTER_WORDS_CREATED @"SIX_PLUS_LETTER_WORDS_CREATED"
#define TOTAL_SCORE @"TOTAL_SCORE"
#define UUID @"UUID"
